### PR TITLE
nit: use close opcode constant

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
I am reading the source code since I started with the same idea last week https://github.com/vigneshshanmugam/turbo-ws-server and I plan to contribute here instead :)

### CODE REVIEW

**Comment by hugmanrique** [comment]
LGTM! Thanks for your help. Will merge when you change that comparison

**Comment by vigneshshanmugam** [comment]
Can you tell me which comparison you are referring to?

**Comment by hugmanrique** [comment]
The constants file has a helper function to check if an opCode is a control opCode. Instead of performing the validation manually (which might change in future versions) we could use that func.

**Comment by vigneshshanmugam** [comment]
Cool, done

**Comment by hugmanrique** [comment]
Thanks for the PR! 😀

**Pull request merged**
